"""
Django settings for InelBackend project.

Generated by 'django-admin startproject' using Django 4.1.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--3@ver0_47s-#i8dm7(q(+js2=2$_!k5#3fh0^ny4*3vn-@8^z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['inelbackend-fccmbmfjbhewhbhh.centralindia-01.azurewebsites.net','localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Should be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'ckeditor',
    'ckeditor_uploader',
    'base',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'InelBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'InelBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Basic': {
            'type': 'basic'
        }
    },
    'USE_SESSION_AUTH': True,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch',
        'head',
        'options',
        'trace'
    ],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none',
    'DEFAULT_MODEL_RENDERING': 'example',
    'DEFAULT_INFO': {
        'title': 'InelBackend API',
        'version': '1.0',
    },
    'PERSIST_AUTH': True,
    'REFETCH_SCHEMA_WITH_AUTH': True,
    'REFETCH_SCHEMA_ON_LOGOUT': True,
}

# CKEditor settings
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

# Allow CKEditor to upload images
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_IMAGE_BACKEND = "pillow"

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # For development only, configure more strictly in production
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React default port
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://inelbackend-fccmbmfjbhewhbhh.centralindia-01.azurewebsites.net",
]

# Disable automatic slash appending
APPEND_SLASH = False

# Site URL for Swagger
SITE_URL = "https://inelbackend-fccmbmfjbhewhbhh.centralindia-01.azurewebsites.net"

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://inelbackend-fccmbmfjbhewhbhh.centralindia-01.azurewebsites.net",
]

# Additional CORS settings for Swagger
CORS_ORIGIN_ALLOW_ALL = True  # Allow all origins (for development)
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'access-control-allow-origin',
    'access-control-allow-headers',
    'access-control-allow-methods',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Jazzmin UI Customizer settings
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark elevation-4",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary btn-flat",
        "secondary": "btn-secondary btn-flat",
        "info": "btn-info btn-flat",
        "warning": "btn-warning btn-flat",
        "danger": "btn-danger btn-flat",
        "success": "btn-success btn-flat"
    },
    "actions_sticky_top": True,
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "base"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "base.AftermarketForm": "fas fa-file-alt",
        "base.ProductType": "fas fa-box",
        "base.Product": "fas fa-boxes",
        "base.Category": "fas fa-tags",
        "base.SubCategory": "fas fa-tag",
        "base.Contact": "fas fa-address-book",
        "base.Newsletter": "fas fa-envelope",
    },
}

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    # title of the window
    "site_title": "Inel Admin",

    # Title on the brand (19 chars max)
    "site_brand": "INEL ADMIN",

    # Title on the login screen
    "site_header": "Inel Technologies",

    # CSS classes that are applied to the logo
    "site_logo_classes": "img-circle",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to Inel Admin Panel",

    # Copyright on the footer
    "copyright": "Inel Technologies Ltd",

    # The model admin to search from the search bar
    "search_model": ["auth.User", "base.AftermarketForm", "base.ProductType", "base.Product", "base.Category"],

    # Field name on user model that contains avatar ImageField/URLField/Charfield
    "user_avatar": None,

    ############
    # Top Menu #
    ############
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"], "icon": "fas fa-tachometer-alt"},
        {"name": "API Docs", "url": "/api/docs/", "new_window": True, "icon": "fas fa-book"},
        {"name": "Support", "url": "mailto:support@inel.com", "icon": "fas fa-question-circle"},
        {"model": "auth.User", "icon": "fas fa-users"},
        {"app": "base", "icon": "fas fa-boxes"},
    ],

    #############
    # Side Menu #
    #############
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # Order of apps/models in the menu
    "order_with_respect_to": ["auth", "base"],

    # Custom icons for side menu apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "base.AftermarketForm": "fas fa-file-alt",
        "base.ProductType": "fas fa-box",
        "base.Product": "fas fa-boxes",
        "base.Category": "fas fa-tags",
        "base.SubCategory": "fas fa-tag",
        "base.Contact": "fas fa-address-book",
        "base.Newsletter": "fas fa-envelope",
    },

    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",

    #############
    # UI Tweaks #
    #############
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    
    # Custom links to append to user menu
    "usermenu_links": [
        {
            "name": "Support",
            "url": "mailto:support@inel.com",
            "icon": "fas fa-question-circle",
        },
        {
            "name": "Documentation",
            "url": "/api/docs/",
            "icon": "fas fa-book",
        },
    ],

    # Custom CSS
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,

    # Sidebar Menu Groups
    "sidebar_menu_groups": [
        {
            "name": "User Management",
            "icon": "fas fa-users",
            "models": ["auth.User", "auth.Group"]
        },
        {
            "name": "Product Management",
            "icon": "fas fa-boxes",
            "models": ["base.ProductType", "base.Product", "base.Category", "base.SubCategory"]
        },
        {
            "name": "Forms & Communication",
            "icon": "fas fa-file-alt",
            "models": ["base.AftermarketForm", "base.Contact", "base.Newsletter"]
        }
    ]
}

