# Generated by Django 4.1.9 on 2025-04-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplication',
            new_name='CareerForm',
        ),
    ]
