# Generated by Django 4.1.9 on 2025-04-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_producttype_vehiclecategory_alter_post_body_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.CreateModel(
            name='FeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/products/features/')),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_images', to='base.product')),
            ],
            options={
                'ordering': ['feature_name'],
                'unique_together': {('product', 'feature_name')},
            },
        ),
    ]
