# Generated by Django 4.1.9 on 2025-04-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_newsletter_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='graph_image',
            field=models.ImageField(blank=True, help_text='Upload product graph or chart image', null=True, upload_to='static/products/graphs/'),
        ),
    ]
