# Generated by Django 5.0.7 on 2025-06-12 11:03

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_graph_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorSubheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Investor Subheading',
                'verbose_name_plural': 'Investor Subheadings',
            },
        ),
        migrations.CreateModel(
            name='InvestorTabHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Investor Tab Heading',
                'verbose_name_plural': 'Investor Tab Headings',
            },
        ),
        migrations.AlterField(
            model_name='featureimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/products/features/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='InvestorSubheadingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('pdf_only', 'PDF Name and Link'), ('title_pdf', 'Title + PDF + Link'), ('ckeditor', 'Title + CKEditor Content')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('editor_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('subheading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='base.investorsubheading')),
            ],
            options={
                'verbose_name': 'Investor Subheading Content',
                'verbose_name_plural': 'Investor Subheading Contents',
            },
        ),
        migrations.AddField(
            model_name='investorsubheading',
            name='tab_heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subheadings', to='base.investortabheading'),
        ),
    ]
