# Generated by Django 5.0.7 on 2025-06-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_investorsubheading_investortabheading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorsubheadingcontent',
            name='content_type',
        ),
    ]
