# Generated by Django 5.2.4 on 2025-07-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_investorsubheadingcontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorsubheadingcontent',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
