# Generated by Django 5.2.4 on 2025-07-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_investorsubheadingcontent_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications_image',
            field=models.ImageField(blank=True, help_text='Optional extra image', null=True, upload_to='static/products/extra/'),
        ),
    ]
