# Generated by Django 4.1.9 on 2025-08-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_product_specifications_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(related_name='products', to='base.producttype'),
        ),
    ]
