# Generated by Django 4.1.9 on 2025-08-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_migrate_product_types'),
        ('base', '0012_remove_product_type_product_types'),
    ]

    operations = [
    ]
