# Generated by Django 5.2.4 on 2025-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_merge_20250801_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producttype',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
