# Generated by Django 5.2.4 on 2025-08-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_product_order_producttype_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='app_img',
            field=models.ImageField(default=2, upload_to='static/products/categories/app/'),
            preserve_default=False,
        ),
    ]
