# Generated by Django 5.2.4 on 2025-08-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_vehiclecategory_app_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scooter_order',
            field=models.IntegerField(default=0, help_text='Specialized ordering for Scooter applications'),
        ),
    ]
