# Generated by Django 5.2.4 on 2025-09-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_add_scooter_order_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='products', to='base.producttype'),
        ),
    ]
