# Generated by Django 5.2.4 on 2025-09-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_product_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investorsubheading',
            options={'ordering': ['order'], 'verbose_name': 'Investor Subheading', 'verbose_name_plural': 'Investor Subheadings'},
        ),
        migrations.AddField(
            model_name='investorsubheading',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
