# Generated by Django 5.2.4 on 2025-09-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_investorsubheading_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investorsubheadingcontent',
            options={'ordering': ['order'], 'verbose_name': 'Investor Subheading Content', 'verbose_name_plural': 'Investor Subheading Contents'},
        ),
        migrations.AddField(
            model_name='investorsubheadingcontent',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
